# Generated by Django 4.0 on 2021-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contact_handle_alter_contact_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
