# Generated by Django 4.0 on 2021-12-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact_source_email_alter_contact_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelTable(
            name='gallery',
            table=None,
        ),
    ]
