# Generated by Django 4.0 on 2021-12-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_gallery_options_alter_gallery_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
